### ISSUE TITLE
Problem with install Calour with conda

### ISSUE THREAD

**Issue by baobabprince** [biocore/calour#155]
I tried to install calour with conda (I add bioconda channel to my list) but it didn't work.
conda couldn't find the correct package for that.

```
(calour) [baobabprince@S-Exupery]$ conda install -c bioconda calour-full  

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - calour-full

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
I also tried to install the non full version and get the same results. Any ideas?

**Comment by RNAer** [comment]
sorry, `calour-full` is not yet built and available on conda. could you install `calour` and its dependencies instead? we corrected the confusion in `INSTALL.md`

**Comment by baobabprince** [comment]
Something is still wrong. I try to use conda to install the standard version and it just print 'Solving environment' for two hours, so I stopped it.
```
(calour) [baobabprince@S-Exupery]$ conda install -c bioconda calour
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: - failed

CondaError: KeyboardInterrupt
```

**Comment by wasade** [comment]
I think this is still an issue. After executing the command [here](https://github.com/biocore/calour/blob/master/INSTALL.md#install-the-latest-manually-from-github-repository), we were unable to finish the `calour` install. 

```
$ conda install -c bioconda calour
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package docrep conflicts for:
calour -> docrep
Package ncurses conflicts for:
python=3.5 -> ncurses[version='>=6.0,<7.0a0|>=6.1,<7.0a0']
Package tk conflicts for:
python=3.5 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0']
Package openssl conflicts for:
python=3.5 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a']
Package libffi conflicts for:
python=3.5 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package ipywidgets conflicts for:
calour -> ipywidgets
Package pandas conflicts for:
calour -> pandas
Package scipy conflicts for:
calour -> scipy
Package scikit-learn conflicts for:
calour -> scikit-learn
Package matplotlib conflicts for:
calour -> matplotlib[version='>=2.0']
Package pyqt conflicts for:
calour -> pyqt[version='>5']
Package statsmodels conflicts for:
calour -> statsmodels
Package pip conflicts for:
python=3.5 -> pip
Package scikit-bio conflicts for:
calour -> scikit-bio[version='>=0.5.1']
Package biom-format conflicts for:
calour -> biom-format
Package numpy conflicts for:
calour -> numpy
Package sqlite conflicts for:
python=3.5 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0']
Package xz conflicts for:
python=3.5 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0']
Package zlib conflicts for:
python=3.5 -> zlib[version='>=1.2.11,<1.3.0a0']
Package readline conflicts for:
python=3.5 -> readline[version='7.*|>=7.0,<8.0a0']
Package ipython conflicts for:
calour -> ipython
Package libcxx conflicts for:
python=3.5 -> libcxx[version='>=4.0.1']
```

**Comment by RNAer** [comment]
Thanks for reporting. I just tried and didn't find the problem on installation. did you create a new env before installing?

```
conda create -n calour python=3.5
conda activate calour
conda install -c bioconda calour
```

**Comment by wasade** [comment]
Yes, using the command noted in the install docs:

```bash
$ conda create -n calour python=3.5 matplotlib numpy scipy pandas qt jupyter scikit-learn statsmodels h5py
```

**Comment by RNAer** [comment]
still can't reproduce the problem

```
$ conda create -n calour python=3.5 matplotlib numpy scipy pandas qt jupyter scikit-learn statsmodels h5py
$ conda install -c bioconda calour
```

**Comment by wasade** [comment]
Weird, let's call it a hiccup then :)

**Comment by RNAer** [comment]
good to know.
